# permissions for end users to edit abstractworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: abstractworkload-editor-role
rules:
- apiGroups:
  - examples.itamar.marom
  resources:
  - abstractworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - examples.itamar.marom
  resources:
  - abstractworkloads/status
  verbs:
  - get
