---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - examples.itamar.marom
  resources:
  - abstractworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - examples.itamar.marom
  resources:
  - abstractworkloads/finalizers
  verbs:
  - update
- apiGroups:
  - examples.itamar.marom
  resources:
  - abstractworkloads/status
  verbs:
  - get
  - patch
  - update
